// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheBuzzerBeater.DataAccess.Data;

#nullable disable

namespace TheBuzzerBeater.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240227141215_AddImageUrlToCategory")]
    partial class AddImageUrlToCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TheBuzzerBeater.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            DisplayOrder = 1,
                            Name = "Jerseys & Apparel"
                        },
                        new
                        {
                            CategoryId = 2,
                            DisplayOrder = 2,
                            Name = "Footwear"
                        },
                        new
                        {
                            CategoryId = 3,
                            DisplayOrder = 3,
                            Name = "Basketball Equipment"
                        },
                        new
                        {
                            CategoryId = 4,
                            DisplayOrder = 4,
                            Name = "Accessories"
                        },
                        new
                        {
                            CategoryId = 5,
                            DisplayOrder = 5,
                            Name = "Sales/Clearance"
                        },
                        new
                        {
                            CategoryId = 10,
                            DisplayOrder = 1,
                            Name = "Air Pumps",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            CategoryId = 11,
                            DisplayOrder = 2,
                            Name = "Arm Sleeves",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            CategoryId = 12,
                            DisplayOrder = 3,
                            Name = "Balls",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            CategoryId = 13,
                            DisplayOrder = 4,
                            Name = "Basket",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            CategoryId = 14,
                            DisplayOrder = 5,
                            Name = "Basketball Nets",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            CategoryId = 15,
                            DisplayOrder = 6,
                            Name = "Beanies",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            CategoryId = 16,
                            DisplayOrder = 7,
                            Name = "Hats",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            CategoryId = 17,
                            DisplayOrder = 8,
                            Name = "Headbands - Wristbands",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            CategoryId = 18,
                            DisplayOrder = 9,
                            Name = "Hoodies",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            CategoryId = 19,
                            DisplayOrder = 10,
                            Name = "Mugs & Cups",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            CategoryId = 20,
                            DisplayOrder = 11,
                            Name = "ΝΒΑ Jerseys",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            CategoryId = 21,
                            DisplayOrder = 12,
                            Name = "ΝΒΑ Retro Jerseys",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            CategoryId = 22,
                            DisplayOrder = 13,
                            Name = "Shoes",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            CategoryId = 23,
                            DisplayOrder = 14,
                            Name = "Socks",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            CategoryId = 24,
                            DisplayOrder = 15,
                            Name = "Stickers",
                            ParentCategoryId = 4
                        });
                });

            modelBuilder.Entity("TheBuzzerBeater.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("OrderHeaderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderHeaderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("TheBuzzerBeater.Models.OrderHeader", b =>
                {
                    b.Property<int>("OrderHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderHeaderId"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Carrier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OrderTotal")
                        .HasColumnType("float");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShippingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderHeaderId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("OrderHeaders");
                });

            modelBuilder.Entity("TheBuzzerBeater.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 19,
                            Description = "Ceramic mugs and cups with your favorite NBA team",
                            ImageUrl = "\\images\\products\\back-me-up-cup-nba-boston-celtics.jpg",
                            Name = "Nba Boston Celtics Cup",
                            Price = 6.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 19,
                            Description = "Ceramic mugs and cups with your favorite NBA team",
                            ImageUrl = "\\images\\products\\back-me-up-cup-nba-bucks.jpg",
                            Name = "Nba Milwaukee Bucks Cup",
                            Price = 6.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 19,
                            Description = "Ceramic mugs and cups with your favorite NBA team",
                            ImageUrl = "\\images\\products\\back-me-up-cup-nba-bulls.jpg",
                            Name = "Nba Chicago Bulls Cup",
                            Price = 6.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 19,
                            Description = "Ceramic mugs and cups with your favorite NBA team",
                            ImageUrl = "\\images\\products\\back-me-up-cup-nba-la-lakers (1).jpg",
                            Name = "Nba Los Angeles Lakers Cup",
                            Price = 6.0
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 19,
                            Description = "Ceramic mugs and cups with your favorite NBA team",
                            ImageUrl = "\\images\\products\\back-me-up-cup-nba-la-lakers.jpg",
                            Name = "Nba Los Angeles Lakers Cup 2",
                            Price = 6.0
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 19,
                            Description = "Ceramic mugs and cups with your favorite NBA team",
                            ImageUrl = "\\images\\products\\back-me-up-cup-nba-logo.jpg",
                            Name = "Nba Logo Cup",
                            Price = 5.0
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 10,
                            Description = "Quickly inflate your favorite ball with the Jordan Essentials Ball Pump. Its compact design makes it easy to carry, and ideal for supplementing the ball air.",
                            ImageUrl = "\\images\\products\\Jordan Essential Ball Pump Intl.jpg",
                            Name = "Jordan Essential Ball Pump Intl",
                            Price = 19.989999999999998
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 10,
                            Description = "This pump is light and easy to use so you can take it with you wherever you go. It is made for all basketballs.",
                            ImageUrl = "\\images\\products\\Nike Essential Ball Pump Intl.jpg",
                            Name = "Nike Essential Ball Pump Intl",
                            Price = 16.989999999999998
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 10,
                            Description = "This pump is light and easy to use so you can take it with you wherever you go. It is made for all basketballs.",
                            ImageUrl = "\\images\\products\\Nike Hyperspeed Ball Pump Intl Swoosh.jpg",
                            Name = "Nike Hyperspeed Ball Pump Intl Swoosh",
                            Price = 24.5
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 10,
                            Description = "The Spalding dual action power pump comes with an attached extension hose. The 12” pump fits all types of valves (includes two different sized needles) and pumps air by pushing and pulling action.",
                            ImageUrl = "\\images\\products\\Spalding 12' Dual Action Power Pump.jpg",
                            Name = "Spalding 12' Dual Action Power Pump",
                            Price = 18.0
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 10,
                            Description = "Dual action Aluminium pump with durable extension hose.",
                            ImageUrl = "\\images\\products\\Wilson Nba Authentic Aluminum Pump.jpg",
                            Name = "Wilson Nba Authentic Aluminum Pump",
                            Price = 21.899999999999999
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 10,
                            Description = "This pump is light and easy to use so you can take it with you wherever you go. It is made for all basketballs.",
                            ImageUrl = "\\images\\products\\Wilson NBA DVR Pump Kit.jpg",
                            Name = "Wilson NBA DVR Pump Kit",
                            Price = 18.600000000000001
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryId = 11,
                            Description = "Compressive Basketball Shooter Sleeves for optimal support on every shot.",
                            ImageUrl = "\\images\\products\\Jordan Unisex Shooter Sleeves.jpg",
                            Name = "Jordan Unisex Shooter Sleeves",
                            Price = 61.990000000000002
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryId = 11,
                            Description = "If you're wondering why you need these COMPRESSPORT Armforce Ultralight Sleeves if you're doing your favorite sports when the weather gets colder, the answer is to provide you with the thermoregulation you need when exposed to cold air. Featuring gentle compression properties, they precisely target core muscles for stimulated blood flow and support. For running, cycling or hiking these sleeves will hug your hands while protecting and keeping them warm.",
                            ImageUrl = "\\images\\products\\COMPRESSPORT Armforce Ultralight.jpg",
                            Name = "COMPRESSPORT Armforce Ultralight",
                            Price = 28.0
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = 11,
                            Description = "Pro Elite Sleeves 2.0, are made with Dri-FIT technology removing sweat for a dry and comfortable feel. Their preformed construction ensures enhanced mobility, while flat seams eliminate friction and irritation.",
                            ImageUrl = "\\images\\products\\Nike Pro Elite SLeeves 2.0.jpg",
                            Name = "Nike Pro Elite SLeeves 2.0 ",
                            Price = 29.899999999999999
                        },
                        new
                        {
                            ProductId = 26,
                            CategoryId = 11,
                            Description = "Compressive Basketball Shooter Sleeves for optimal support on every shot.",
                            ImageUrl = "\\images\\products\\Nike Pro Elbow Sleeve 3.0.jpg",
                            Name = "Nike Pro Elbow Sleeve 3.0",
                            Price = 22.949999999999999
                        },
                        new
                        {
                            ProductId = 27,
                            CategoryId = 11,
                            Description = "Compressive Basketball Shooter Sleeves for optimal support on every shot.",
                            ImageUrl = "\\images\\products\\Nike Pro Ankle Sleeve 3.0.jpg",
                            Name = "Nike Pro Ankle Sleeve 3.0",
                            Price = 21.989999999999998
                        },
                        new
                        {
                            ProductId = 28,
                            CategoryId = 11,
                            Description = "Utilised by the best in the game to improve performance, these form fitting sleeves provide superior support and protection. The compression fit allows a wide range of motion and muscle support. The Dri-FIT fabric wicks moisture away for comfort.Sold in pairs",
                            ImageUrl = "\\images\\products\\Jordan Unisex Shooter Sleeves.jpg",
                            Name = "Nike NBA 2.0 Basketball Shooter Sleeve",
                            Price = 34.5
                        },
                        new
                        {
                            ProductId = 29,
                            CategoryId = 11,
                            Description = "Compressive Basketball Shooter Sleeves for optimal support on every shot.",
                            ImageUrl = "\\images\\products\\Mcdavid Hex Shooter Arm SLeeve.jpg",
                            Name = "Mcdavid Hex Shooter Arm SLeeve",
                            Price = 30.0
                        },
                        new
                        {
                            ProductId = 30,
                            CategoryId = 11,
                            Description = "Compressive Basketball Shooter Sleeves for optimal support on every shot.",
                            ImageUrl = "\\images\\products\\Mcdavid Power Shooter Arm SLeeve.jpg",
                            Name = "Mcdavid Power Shooter Arm SLeeve",
                            Price = 27.989999999999998
                        },
                        new
                        {
                            ProductId = 31,
                            CategoryId = 11,
                            Description = "Compressive Basketball Shooter Sleeves for optimal support on every shot.",
                            ImageUrl = "\\images\\products\\MCDAVID Elite Compression Arm Sleeve.jpg",
                            Name = "MCDAVID Elite Compression Arm Sleeve",
                            Price = 24.989999999999998
                        },
                        new
                        {
                            ProductId = 32,
                            CategoryId = 12,
                            Description = "Nike Playground 8P 2.0 G Antetokounmpo Deflated",
                            ImageUrl = "\\images\\products\\Nike Playground 8P 2.0 G Antetokounmpo Deflated.jpg",
                            Name = "Nike Playground 8P 2.0 G Antetokounmpo Deflated Basketball",
                            Price = 33.5
                        },
                        new
                        {
                            ProductId = 33,
                            CategoryId = 12,
                            Description = "The SKLZ Control basketball is the perfect training ball to help athletes improve their dribbling skills. It is made of high quality synthetic leather for indoor and outdoor training.",
                            ImageUrl = "\\images\\products\\SKLZ Lightweight Control Basketball Ball.jpg",
                            Name = "SKLZ Lightweight Control Basketball ",
                            Price = 39.899999999999999
                        },
                        new
                        {
                            ProductId = 34,
                            CategoryId = 12,
                            Description = "Nike All Court 8P Z Williamson Deflated",
                            ImageUrl = "\\images\\products\\Nike All Court 8P Z Williamson Deflated.jpg",
                            Name = "Nike All Court 8P Z Williamson Deflated Basketball",
                            Price = 51.5
                        },
                        new
                        {
                            ProductId = 35,
                            CategoryId = 12,
                            Description = "Nike Basketball 8P Energy Deflated",
                            ImageUrl = "\\images\\products\\Nike Basketball 8P Energy Deflated.jpg",
                            Name = "Nike Basketball 8P Energy Deflated ",
                            Price = 57.149999999999999
                        },
                        new
                        {
                            ProductId = 36,
                            CategoryId = 12,
                            Description = "Nike Elite Tournament 8P Deflated",
                            ImageUrl = "\\images\\products\\Nike Elite Tournament 8P Deflated.jpg",
                            Name = "Nike Elite Tournament 8P Deflated Basketball",
                            Price = 68.900000000000006
                        },
                        new
                        {
                            ProductId = 37,
                            CategoryId = 12,
                            Description = "Wilson Nba Official Game Ball Bskt Retail",
                            ImageUrl = "\\images\\products\\Wilson Nba Official Game Ball Bskt Retail.jpg",
                            Name = "Wilson Nba Official Game Basketball Retail",
                            Price = 259.0
                        },
                        new
                        {
                            ProductId = 38,
                            CategoryId = 12,
                            Description = "Nike Championship 8P Deflated",
                            ImageUrl = "\\images\\products\\Nike Championship 8P Deflated.jpg",
                            Name = "Nike Championship 8P Deflated Basketball",
                            Price = 104.0
                        },
                        new
                        {
                            ProductId = 39,
                            CategoryId = 12,
                            Description = "Nike Basketball 8P Prm Energy Deflated",
                            ImageUrl = "\\images\\products\\Nike Basketball 8P Prm Energy Deflated.jpg",
                            Name = "Nike Basketball 8P Prm Energy Deflated",
                            Price = 57.509999999999998
                        },
                        new
                        {
                            ProductId = 40,
                            CategoryId = 12,
                            Description = "Nike Skills",
                            ImageUrl = "\\images\\products\\Nike Skills.jpg",
                            Name = "Nike Skills Basketball",
                            Price = 13.5
                        },
                        new
                        {
                            ProductId = 41,
                            CategoryId = 12,
                            Description = "Nike Everyday All Court 8P Graphic Deflated",
                            ImageUrl = "\\images\\products\\Nike Everyday All Court 8P Graphic Deflated.jpg",
                            Name = "Nike Everyday All Court 8P Graphic Deflated Basketball",
                            Price = 39.899999999999999
                        },
                        new
                        {
                            ProductId = 42,
                            CategoryId = 12,
                            Description = "Nike Ultimate 2.0 8P Graphic Deflated",
                            ImageUrl = "\\images\\products\\Nike Ultimate 2.0 8P Graphic Deflated.jpg",
                            Name = "Nike Ultimate 2.0 8P Graphic Deflated Basketball",
                            Price = 44.899999999999999
                        },
                        new
                        {
                            ProductId = 43,
                            CategoryId = 13,
                            Description = "You don’t need a court to get shots up. Play anywhere with the Team Mini Hoop. Represent your squad with the team paint splatter style. This hoop fits over your doorway with easy assembly for quick set up.",
                            ImageUrl = "\\images\\products\\Wilson NBA Milwaukee Bucks Mini Hoop.jpg",
                            Name = "Wilson NBA Milwaukee Bucks Mini Hoop",
                            Price = 27.399999999999999
                        },
                        new
                        {
                            ProductId = 44,
                            CategoryId = 13,
                            Description = "Basketball Dashboard set",
                            ImageUrl = "\\images\\products\\Amila Basketball Dashboard 16Mm.jpg",
                            Name = "Amila Basketball Dashboard 16Mm",
                            Price = 115.90000000000001
                        },
                        new
                        {
                            ProductId = 45,
                            CategoryId = 13,
                            Description = "Amila Basketball With Hoop Net 2.27-3.05M",
                            ImageUrl = "\\images\\products\\Amila Basketball With Hoop Net 2.27-3.05M.jpg",
                            Name = "Amila Basketball With Hoop Net 2.27-3.05M",
                            Price = 279.89999999999998
                        },
                        new
                        {
                            ProductId = 46,
                            CategoryId = 13,
                            Description = "Amila handheld basket with adjustable height for family play. Ideal for indoor and outdoor use. Dashboard made of durable polycarbonate material with steel edging. The vinyl base is filled with water or sand for guaranteed stability in play.",
                            ImageUrl = "\\images\\products\\Amila Basket Semi-Professional, Thickness 3.0Mm.jpg",
                            Name = "Amila Basket Semi-Professional, Thickness 3.0Mm.jpg",
                            Price = 374.89999999999998
                        },
                        new
                        {
                            ProductId = 47,
                            CategoryId = 13,
                            Description = "SKLZ Pro Mini Hoop System",
                            ImageUrl = "\\images\\products\\SKLZ Pro Mini Hoop System.jpg",
                            Name = "SKLZ Pro Mini Hoop System",
                            Price = 219.94999999999999
                        },
                        new
                        {
                            ProductId = 48,
                            CategoryId = 13,
                            Description = "Portable basketball from the Highlight series of Spalding. With acrylic board width 42 '' and variable height from 2.28 to 3.05 meters so that both the youngest and the oldest basketball fans can enjoy the game!",
                            ImageUrl = "\\images\\products\\Spalding 2015 Highlight Portable 42'' Acrylic.jpg",
                            Name = "Spalding 2015 Highlight Portable 42'' Acrylic",
                            Price = 435.60000000000002
                        },
                        new
                        {
                            ProductId = 49,
                            CategoryId = 13,
                            Description = "Amila Backboard with three-colour net.",
                            ImageUrl = "\\images\\products\\Amila Backboard 122 x 85 cm 49197.jpg",
                            Name = "Amila Backboard 122 x 85 cm 49197",
                            Price = 219.90000000000001
                        },
                        new
                        {
                            ProductId = 50,
                            CategoryId = 13,
                            Description = "Amila Basketball Hoop with Springs & Net.",
                            ImageUrl = "\\images\\products\\Amila Basketball Hoop with Springs & Net.jpg",
                            Name = "Amila Basketball Hoop with Springs & Net",
                            Price = 67.900000000000006
                        },
                        new
                        {
                            ProductId = 51,
                            CategoryId = 13,
                            Description = "Basket wreath with steel tube and spring for pressure absorption from ball hitting and hanging by players. Its diameter is 45cm and includes net in the package. Suitable for every dashboard and basketball to play on the court, garden or cottage.",
                            ImageUrl = "\\images\\products\\Amila Basketball Hoop.jpg",
                            Name = "Amila Basketball Hoop",
                            Price = 64.900000000000006
                        },
                        new
                        {
                            ProductId = 52,
                            CategoryId = 14,
                            Description = "This pump is light and easy to use so you can take it with you wherever you go. It is made for all basketballs.",
                            ImageUrl = "\\images\\products\\Wilson NBA DVR Pump Kit.jpg",
                            Name = "Wilson NBA DVR Pump Kit",
                            Price = 18.600000000000001
                        },
                        new
                        {
                            ProductId = 64,
                            CategoryId = 15,
                            Description = "This pump is light and easy to use so you can take it with you wherever you go. It is made for all basketballs.",
                            ImageUrl = "\\images\\products\\Wilson NBA DVR Pump Kit.jpg",
                            Name = "Wilson NBA DVR Pump Kit",
                            Price = 18.600000000000001
                        },
                        new
                        {
                            ProductId = 74,
                            CategoryId = 16,
                            Description = "This pump is light and easy to use so you can take it with you wherever you go. It is made for all basketballs.",
                            ImageUrl = "\\images\\products\\Wilson NBA DVR Pump Kit.jpg",
                            Name = "Wilson NBA DVR Pump Kit",
                            Price = 18.600000000000001
                        },
                        new
                        {
                            ProductId = 84,
                            CategoryId = 17,
                            Description = "This pump is light and easy to use so you can take it with you wherever you go. It is made for all basketballs.",
                            ImageUrl = "\\images\\products\\Wilson NBA DVR Pump Kit.jpg",
                            Name = "Wilson NBA DVR Pump Kit",
                            Price = 18.600000000000001
                        },
                        new
                        {
                            ProductId = 94,
                            CategoryId = 18,
                            Description = "This pump is light and easy to use so you can take it with you wherever you go. It is made for all basketballs.",
                            ImageUrl = "\\images\\products\\Wilson NBA DVR Pump Kit.jpg",
                            Name = "Wilson NBA DVR Pump Kit",
                            Price = 18.600000000000001
                        },
                        new
                        {
                            ProductId = 104,
                            CategoryId = 20,
                            Description = "This pump is light and easy to use so you can take it with you wherever you go. It is made for all basketballs.",
                            ImageUrl = "\\images\\products\\Wilson NBA DVR Pump Kit.jpg",
                            Name = "Wilson NBA DVR Pump Kit",
                            Price = 18.600000000000001
                        },
                        new
                        {
                            ProductId = 114,
                            CategoryId = 21,
                            Description = "This pump is light and easy to use so you can take it with you wherever you go. It is made for all basketballs.",
                            ImageUrl = "\\images\\products\\Wilson NBA DVR Pump Kit.jpg",
                            Name = "Wilson NBA DVR Pump Kit",
                            Price = 18.600000000000001
                        },
                        new
                        {
                            ProductId = 124,
                            CategoryId = 22,
                            Description = "This pump is light and easy to use so you can take it with you wherever you go. It is made for all basketballs.",
                            ImageUrl = "\\images\\products\\Wilson NBA DVR Pump Kit.jpg",
                            Name = "Wilson NBA DVR Pump Kit",
                            Price = 18.600000000000001
                        },
                        new
                        {
                            ProductId = 134,
                            CategoryId = 23,
                            Description = "This pump is light and easy to use so you can take it with you wherever you go. It is made for all basketballs.",
                            ImageUrl = "\\images\\products\\Wilson NBA DVR Pump Kit.jpg",
                            Name = "Wilson NBA DVR Pump Kit",
                            Price = 18.600000000000001
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 24,
                            Description = "A pack of two stickers featuring your favourite NBA team!",
                            ImageUrl = "\\images\\products\\Back Me Up NBA Brooklyn Nets Stickers.jpg",
                            Name = "NBA Brooklyn Nets Stickers",
                            Price = 0.90000000000000002
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 24,
                            Description = "A pack of two stickers featuring your favourite NBA team!",
                            ImageUrl = "\\images\\products\\Back Me Up NBA Chicago Bulls Stickers.png",
                            Name = "NBA Chicago Bulls Stickers",
                            Price = 0.90000000000000002
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 24,
                            Description = "A pack of two stickers featuring your favourite NBA team!",
                            ImageUrl = "\\images\\products\\Back Me Up NBA Dallas Mavericks Stickers.png",
                            Name = "NBA Dallas Mavericks Stickers",
                            Price = 0.90000000000000002
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 24,
                            Description = "A pack of two stickers featuring your favourite NBA team!",
                            ImageUrl = "\\images\\products\\Back Me Up NBA Golden State Stickers.jpg",
                            Name = "NBA Golden State Stickers",
                            Price = 0.90000000000000002
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 24,
                            Description = "A pack of two stickers featuring your favourite NBA team!",
                            ImageUrl = "\\images\\products\\Back Me Up NBA Milwauke Bucks Stickers.png",
                            Name = "NBA Milwauke Bucks Stickers",
                            Price = 0.90000000000000002
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 24,
                            Description = "A pack of two stickers featuring your favourite NBA team!",
                            ImageUrl = "\\images\\products\\Back Me Up NBA Stickers.jpg",
                            Name = "NBA Stickers",
                            Price = 0.90000000000000002
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 24,
                            Description = "A pack of two stickers featuring your favourite NBA team!",
                            ImageUrl = "\\images\\products\\Back Me Up Phoenix Suns Stickers.jpg",
                            Name = "NBA Phoenix Suns Stickers",
                            Price = 0.90000000000000002
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 24,
                            Description = "A pack of two stickers featuring your favourite NBA team!",
                            ImageUrl = "\\images\\products\\Back Me Up Pvc Stickers Nba Boston Celtics.jpg",
                            Name = "Nba Boston Celtics Stickers",
                            Price = 0.90000000000000002
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 24,
                            Description = "A pack of two stickers featuring your favourite NBA team!",
                            ImageUrl = "\\images\\products\\Back Me Up Pvc Stickers Ny Knics.jpg",
                            Name = "NBA New York Knicks Stickers",
                            Price = 0.90000000000000002
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 24,
                            Description = "A pack of two stickers featuring your favourite NBA team!",
                            ImageUrl = "\\images\\products\\Back Me Up NBA Los Angeles Lakers Stickers.jpg",
                            Name = "NBA Los Angeles Lakers Stickers",
                            Price = 0.90000000000000002
                        });
                });

            modelBuilder.Entity("TheBuzzerBeater.Models.ShoppingCart", b =>
                {
                    b.Property<int>("ShoppingCartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoppingCartId"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCartId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("TheBuzzerBeater.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(100)");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheBuzzerBeater.Models.Category", b =>
                {
                    b.HasOne("TheBuzzerBeater.Models.Category", "ParentCategory")
                        .WithMany("Subcategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("TheBuzzerBeater.Models.OrderDetail", b =>
                {
                    b.HasOne("TheBuzzerBeater.Models.OrderHeader", "OrderHeader")
                        .WithMany()
                        .HasForeignKey("OrderHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBuzzerBeater.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderHeader");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TheBuzzerBeater.Models.OrderHeader", b =>
                {
                    b.HasOne("TheBuzzerBeater.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("TheBuzzerBeater.Models.Product", b =>
                {
                    b.HasOne("TheBuzzerBeater.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TheBuzzerBeater.Models.ShoppingCart", b =>
                {
                    b.HasOne("TheBuzzerBeater.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBuzzerBeater.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TheBuzzerBeater.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Subcategories");
                });
#pragma warning restore 612, 618
        }
    }
}
