// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheBuzzerBeater.DataAccess.Data;

#nullable disable

namespace TheBuzzerBeater.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheBuzzerBeater.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            DisplayOrder = 1,
                            Name = "Air Pumps"
                        },
                        new
                        {
                            CategoryId = 2,
                            DisplayOrder = 2,
                            Name = "Arm Sleeves"
                        },
                        new
                        {
                            CategoryId = 3,
                            DisplayOrder = 3,
                            Name = "Balls"
                        },
                        new
                        {
                            CategoryId = 4,
                            DisplayOrder = 4,
                            Name = "Basket"
                        },
                        new
                        {
                            CategoryId = 5,
                            DisplayOrder = 5,
                            Name = "Basketball Nets"
                        },
                        new
                        {
                            CategoryId = 6,
                            DisplayOrder = 6,
                            Name = "Beanies"
                        },
                        new
                        {
                            CategoryId = 7,
                            DisplayOrder = 7,
                            Name = "Hats"
                        },
                        new
                        {
                            CategoryId = 8,
                            DisplayOrder = 8,
                            Name = "Headbands - Wristbands"
                        },
                        new
                        {
                            CategoryId = 9,
                            DisplayOrder = 9,
                            Name = "Hoodies"
                        },
                        new
                        {
                            CategoryId = 10,
                            DisplayOrder = 10,
                            Name = "Mugs & Cups"
                        },
                        new
                        {
                            CategoryId = 11,
                            DisplayOrder = 11,
                            Name = "ΝΒΑ Jerseys"
                        },
                        new
                        {
                            CategoryId = 12,
                            DisplayOrder = 12,
                            Name = "Shoes"
                        },
                        new
                        {
                            CategoryId = 13,
                            DisplayOrder = 13,
                            Name = "Socks"
                        },
                        new
                        {
                            CategoryId = 14,
                            DisplayOrder = 14,
                            Name = "Stickers"
                        });
                });

            modelBuilder.Entity("TheBuzzerBeater.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 10,
                            Description = "Ceramic mugs and cups with your favorite NBA team",
                            ImageUrl = "@/images/product/back-me-up-koupa-keramapli-nba-boston-celtics.jpg",
                            Name = "back-me-up-cup-nba-boston-celtics",
                            Price = 6.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 10,
                            Description = "Ceramic mugs and cups with your favorite NBA team",
                            ImageUrl = "@/images/product/back-me-up-koupa-keramapli-nba-bucks",
                            Name = "back-me-up-cup-nba-bucks",
                            Price = 6.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 10,
                            Description = "Ceramic mugs and cups with your favorite NBA team",
                            ImageUrl = "@/images/product/back-me-up-koupa-keramapli-nba-bulls",
                            Name = "back-me-up-cup-nba-bulls",
                            Price = 6.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 10,
                            Description = "Ceramic mugs and cups with your favorite NBA team",
                            ImageUrl = "@/images/product/back-me-up-koupa-keramapli-nba-la-lakers (1)",
                            Name = "back-me-up-cup-nba-la-lakers",
                            Price = 6.0
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 10,
                            Description = "Ceramic mugs and cups with your favorite NBA team",
                            ImageUrl = "@/images/product/back-me-up-koupa-keramapli-nba-la-lakers",
                            Name = "back-me-up-cup-nba-la-lakers-second",
                            Price = 6.0
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 10,
                            Description = "Ceramic mugs and cups with your favorite NBA team",
                            ImageUrl = "@/images/product/back-me-up-koupa-keramapli-nba-logo",
                            Name = "back-me-up-cup-nba-logo",
                            Price = 5.0
                        });
                });

            modelBuilder.Entity("TheBuzzerBeater.Models.Product", b =>
                {
                    b.HasOne("TheBuzzerBeater.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
